### ISSUE TITLE
roadmap discussion

### ISSUE THREAD

**Issue by benjie** [stlbucket/postgraphile-db-inspector-extension#3]

**Comment by stlbucket** [comment]
https://github.com/stlbucket/postgraphile-db-inspector-extension/blob/master/roadmap.md

i created a brain-dump of what this tool could do.  let's discuss here and i'll change that file accordingly.

**Comment by benjie** [comment]
> big question is it possible this tool should operate on the introspection results of the actual server instead of at table level?


Probably; smart comments are a bit of a hack, we can totally use a plugin to replace/supplement them.

> special note - instead of 'smart comment', could we call these things schemutators (schema mutators)?
> they could still be expressed as smart comments, but if we build the above plugin, then that kinda goes away

We call them "tags" internally, as in "tag it with `@omit`" or "tag it with a new name".

> for instance, you might want all 'created_at' fields to be omitted from create/insert/update mutations on all tables

This is generally better served with RBAC, but we can totally do that with the tags plugin.

> i am strongly considering refactoring the existing tools such that they are themselves plugins to this tool. it would be cool to make it easy for the community to extend this in this future.


I'm a big fan of plugins ;)

> or build our own

Recommend not biting off more than you can chew, this project's already pretty ambitious!
